"""
Regenerates the Squarespace embed bundle from the live source files.

Run from the repo root (or anywhere):  python squarespace/build.py

Outputs, in this folder:
  header-injection.html   -> Settings > Advanced > Code Injection > HEADER
  footer-injection.html   -> Settings > Advanced > Code Injection > FOOTER
  page-code-block.html    -> paste into a single Code Block on a blank page

ASSET_BASE is the public root URL where css/, js/ and assets/ are served.
Re-run this script whenever index.html changes so the code block stays
in sync with local development.
"""

import re
from pathlib import Path

# ── Config ──────────────────────────────────────────────────────────
# Public root that serves this repo's files, WITH trailing slash.
# jsDelivr (requires the GitHub repo to be public):
ASSET_BASE = "https://cdn.jsdelivr.net/gh/silencekillsdesign/TEDxChicago2026@main/"
# Alternative: Squarespace-hosted files (see README) would instead use
# per-file /s/ URLs; in that case set ASSET_BASE = "/s/" and upload the
# assets flat, or keep absolute URLs per file.

ROOT = Path(__file__).resolve().parent.parent
OUT = Path(__file__).resolve().parent

# ── Page code block: everything inside <body>, minus the script tag ─
html = (ROOT / "index.html").read_text(encoding="utf-8")

m = re.search(r"<body>(.*)</body>", html, flags=re.S)
if not m:
    raise SystemExit("Could not locate <body>...</body> in index.html")
body = m.group(1)

# The JS include moves to footer injection.
body = re.sub(r'\s*<script src="js/main\.js[^"]*"></script>', "", body)

# Point every relative asset reference at the CDN.
body = body.replace('src="assets/', f'src="{ASSET_BASE}assets/')

code_block = (
    "<!-- TEDxChicago 2026 - page content.\n"
    "     Generated by squarespace/build.py - edit index.html, then re-run\n"
    "     the script and re-paste. Requires the header/footer injections. -->\n"
    + body.strip()
    + "\n"
)
(OUT / "page-code-block.html").write_text(code_block, encoding="utf-8")

# ── Header injection ────────────────────────────────────────────────
# Pull the Event JSON-LD straight from index.html so there's a single
# source of truth. (OG/Twitter tags are intentionally NOT injected —
# set those in Squarespace's own Page SEO / social-sharing panel to
# avoid duplicate og: tags fighting Squarespace's generated ones.)
ld = re.search(
    r'<script type="application/ld\+json">.*?</script>', html, flags=re.S
)
json_ld = ld.group(0) if ld else ""

header = f"""<!-- TEDxChicago 2026 - paste into the EVENT PAGE's
     Page Settings > Advanced > Page Header Code Injection (NOT site-wide). -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Handjet:wght@300;400;500;600;700&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{ASSET_BASE}css/styles.css">

{json_ld}
"""
(OUT / "header-injection.html").write_text(header, encoding="utf-8")

# ── Footer injection ────────────────────────────────────────────────
footer = f"""<!-- TEDxChicago 2026 - paste into Settings > Advanced > Code Injection > FOOTER -->
<script>window.TEDX_ASSET_BASE = "{ASSET_BASE}";</script>
<script src="{ASSET_BASE}js/main.js" defer></script>
"""
(OUT / "footer-injection.html").write_text(footer, encoding="utf-8")

print(f"page-code-block.html : {len(code_block):,} chars")
print(f"header-injection.html: {len(header):,} chars")
print(f"footer-injection.html: {len(footer):,} chars")
print(f"ASSET_BASE = {ASSET_BASE}")
